"""empty message

Revision ID: a29265135a47
Revises: f62fcd8c7602
Create Date: 2026-02-08 11:37:56.295412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a29265135a47'
down_revision: Union[str, Sequence[str], None] = 'f62fcd8c7602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('nr_members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band', 'nr_members')
    # ### end Alembic commands ###
